name: Deploy Frontend to Azure App Service

on:
  push:
    branches:
      - main
    paths:
      - 'src/ResumeAnalyzer.Web/**'
      - 'src/ResumeAnalyzer.Domain/**'
      - 'src/ResumeAnalyzer.Infrastructure/**'
      - 'ResumeAnalyzer.sln'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Source Code
      uses: actions/checkout@v4

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore ResumeAnalyzer.sln

    - name: Build Solution
      run: dotnet build ResumeAnalyzer.sln --configuration Release --no-restore

    - name: Publish Presentation Project
      run: dotnet publish src/ResumeAnalyzer.Web/ResumeAnalyzer.Web.csproj --configuration Release -o ${{ runner.temp }}/publish-app --no-build

    - name: Deploy to Azure WebApp
      uses: azure/webapps-deploy@v3
      with:
        app-name: 'resume-analyzer-web-app' # Replace with your Azure Web App Name
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ${{ runner.temp }}/publish-app
